### ISSUE TITLE
Failed to build - TypeError: babel.Transformer is not a function

### ISSUE THREAD

**Issue by pionl** [danielberndt/babel-plugin-utf-8-regex#1]
Hi Daniel,

I've added the plugin into the `.babelrc` and while building it throws an error.
I'm using a 6.8.1 babel-core

Thank you

```
Module build failed: TypeError: babel.Transformer is not a function
    at exports.default (...frontend/node_modules/babel-plugin-utf-8-regex/modules/index.js:14:10)
    at Function.memoisePluginContainer (frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:134:13)
    at Function.normali
```

**Comment by danielberndt** [comment]
Hey @pionl,

This plugin was written in babel 5.x times and doesn't seem to be forward compatible. I actually haven't checked yet, how the upgrade path is. I guess this is a good opportunity to figure this out!

**Comment by catamphetamine** [comment]
There seems to be no actual "migration guide" for plugin developers when upgrading from 5 to 6.
https://babeljs.io/blog/2015/10/29/6.0.0

The only note in their blog post is that this: 

```js
export default function({ Plugin, types: t }) {
  return new Plugin(‘ast-transform’, {
    visitor: { … }
  });
}
```

Becomes this:

```js
export default function({ types: t }) {
  return {
    visitor: { … }
  };
}
```

My guess is that `index.js` should be changed to:

```js
import transformer from "./transformer";

export default function(babel) {
  return {
    visitor: {
      Literal: function(path) {
        var node = path.node;
        if (node.regex) {
          return transformer(node.regex.pattern, node.regex.flags).toString();
        }
      }
    }
  }
}
```

According to this example:
https://github.com/codemix/babel-plugin-closure-elimination/pull/4

So, someone could edit `node_modules/babel-plugin-closure-elimination/modules/index.js` file manually.
https://npmcdn.com/babel-plugin-utf-8-regex@0.1.1/modules/index.js
And see.

**Comment by danielberndt** [comment]
Thanks for all your work!
I've just updated all the code and made it work in Babel 6. Turned out I needed to change quite a bit to make it work.

I also discovered that babel now has an official plugin for this:
https://github.com/babel/babel/blob/master/packages/babel-plugin-proposal-unicode-property-regex/README.md

This means that this repo probably isn't needed any longer anyways :)

**Comment by catamphetamine** [comment]
Oh, cool )
Not to mention Babel 7 is around the corner.
